import streamlit as st
import pandas as pd
import datetime
import os
import base64
from io import BytesIO
import random
from copy import deepcopy

# --- PAGE CONFIG ---
st.set_page_config(page_title="VPS Timetable Manager", layout="wide")

# ============================================================
# 🔐 PASSWORD PROTECTION
# ============================================================
def check_password():
    """Returns True if the user entered the correct password."""
    def password_entered():
        if st.session_state["password"] == st.secrets["APP_PASSWORD"]:
            st.session_state["password_correct"] = True
            del st.session_state["password"]
        else:
            st.session_state["password_correct"] = False

    if st.session_state.get("password_correct", False):
        return True

    st.markdown("""
        <style>
            .login-box {
                max-width: 400px; margin: 100px auto; padding: 40px;
                background: linear-gradient(135deg, #004d4d, #006666);
                border-radius: 20px; text-align: center; color: white;
                box-shadow: 0 10px 30px rgba(0,0,0,0.3);
            }
            .stTextInput>div>div>input {
                text-align: center; border-radius: 30px !important;
                border: 2px solid #009999 !important;
            }
        </style>
    """, unsafe_allow_html=True)

    st.markdown('<div class="login-box">', unsafe_allow_html=True)
    st.markdown("### 🔐 VPS Timetable Manager")
    st.markdown("Please enter the password to continue.")
    st.text_input("Password", type="password", key="password", on_change=password_entered, placeholder="Enter password...")
    st.markdown('</div>', unsafe_allow_html=True)

    if not st.session_state.get("password_correct", False):
        st.error("❌ Incorrect password. Please try again.")
    return False

if not check_password():
    st.stop()

# ============================================================
# 🎨 CSS STYLING
# ============================================================
st.markdown("""
    <style>
        .main-header {
            background: linear-gradient(135deg, #004d4d, #006666, #009999);
            color: white; padding: 15px; border-radius: 15px;
            text-align: center; margin-bottom: 20px;
        }
        .stButton>button { background-color: #006666; color: white; border-radius: 8px; }
        .stButton>button:hover { background-color: #009999; color: white; }
        .logout-btn { position: fixed; top: 10px; right: 10px; z-index: 999; }
        .gen-header { background: #e0f7f7; padding: 15px; border-radius: 10px; border-left: 5px solid #006666; margin-bottom: 15px; }
        .subject-tag {
            display: inline-block; padding: 4px 12px; margin: 3px;
            border-radius: 15px; font-size: 13px; font-weight: bold;
        }
    </style>
""", unsafe_allow_html=True)

col_logo, col_logout = st.columns([6, 1])
with col_logo:
    st.markdown('<div class="main-header"><h2>🏫 VPS Timetable & Substitution Manager</h2></div>', unsafe_allow_html=True)
with col_logout:
    if st.button("🚪 Logout", key="logout"):
        st.session_state.password_correct = False
        st.rerun()

# ============================================================
# 📄 PDF EXPORT FUNCTION
# ============================================================
def generate_pdf(df, title):
    html_rows = ""
    for _, row in df.iterrows():
        html_rows += "<tr>" + "".join(f"<td>{str(val)}</td>" for val in row) + "</tr>"
    columns = "".join(f"<th>{col}</th>" for col in df.columns)
    html_content = f"""
    <!DOCTYPE html><html><head><meta charset="UTF-8"><title>{title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; padding: 20px; }}
        h2 {{ color: #004d4d; text-align: center; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th {{ background-color: #006666; color: white; padding: 10px; text-align: left; }}
        td {{ padding: 8px; border-bottom: 1px solid #ddd; }}
        tr:nth-child(even) {{ background-color: #f2f2f2; }}
        .footer {{ text-align: center; margin-top: 30px; font-size: 12px; color: #888; }}
    </style></head><body>
        <h2>{title}</h2>
        <table><thead><tr>{columns}</tr></thead><tbody>{html_rows}</tbody></table>
        <div class="footer">Generated by VPS Timetable Manager on {datetime.date.today()}</div>
    </body></html>
    """
    b64 = base64.b64encode(html_content.encode()).decode()
    href = f'<a href="data:text/html;base64,{b64}" download="{title.replace(" ", "_")}.html" style="display: inline-block; padding: 10px 20px; background-color: #006666; color: white; text-decoration: none; border-radius: 8px; font-weight: bold;">📥 Download as HTML (Print to PDF)</a>'
    return href

# ============================================================
# 🕒 TIMETABLE GENERATOR ENGINE
# ============================================================

def generate_timetable(classes_data, teachers_data, days_list, periods_per_day):
    """
    Generate a clash-free timetable.
    
    classes_data: dict of {class_name: {subject: periods_per_week}}
    teachers_data: dict of {teacher_name: [list of subjects they teach]}
    days_list: list of day names
    periods_per_day: int
    
    Returns: dict of {class_name: {day: {period: subject}}}
             and dict of {teacher_name: {day: {period: class_name}}}
    """
    
    # Initialise empty grids
    class_grid = {}
    teacher_grid = {}
    
    for cls in classes_data:
        class_grid[cls] = {day: {p: None for p in range(1, periods_per_day + 1)} for day in days_list}
    
    for teacher in teachers_data:
        teacher_grid[teacher] = {day: {p: None for p in range(1, periods_per_day + 1)} for day in days_list}
    
    # Build reverse mapping: subject -> list of teachers
    subject_to_teachers = {}
    for teacher, subjects in teachers_data.items():
        for subj in subjects:
            if subj not in subject_to_teachers:
                subject_to_teachers[subj] = []
            subject_to_teachers[subj].append(teacher)
    
    # For each class, schedule subjects
    for cls, subjects_dict in classes_data.items():
        # Create a list of all subject slots to fill
        all_slots = []
        for subject, count in subjects_dict.items():
            for _ in range(count):
                all_slots.append(subject)
        
        # Shuffle for randomness
        random.shuffle(all_slots)
        
        # Get available days and periods
        all_day_periods = []
        for day in days_list:
            for p in range(1, periods_per_day + 1):
                all_day_periods.append((day, p))
        random.shuffle(all_day_periods)
        
        slot_idx = 0
        for subject in all_slots:
            placed = False
            
            # Try to find a slot for this subject
            for day, p in all_day_periods:
                if class_grid[cls][day][p] is not None:
                    continue
                
                # Find a teacher for this subject
                teachers_for_subj = subject_to_teachers.get(subject, [])
                random.shuffle(teachers_for_subj)
                
                for teacher in teachers_for_subj:
                    if teacher_grid[teacher][day][p] is None:
                        # Place it!
                        class_grid[cls][day][p] = (subject, teacher)
                        teacher_grid[teacher][day][p] = cls
                        placed = True
                        break
                
                if placed:
                    break
            
            if not placed:
                # Fallback: force place in first empty slot
                for day, p in all_day_periods:
                    if class_grid[cls][day][p] is None:
                        teachers_for_subj = subject_to_teachers.get(subject, ["Unassigned"])
                        teacher = teachers_for_subj[0] if teachers_for_subj else "Unassigned"
                        class_grid[cls][day][p] = (subject, teacher)
                        if teacher != "Unassigned":
                            teacher_grid[teacher][day][p] = cls
                        placed = True
                        break
    
    return class_grid, teacher_grid


def grid_to_dataframe(class_grid, days_list, periods_per_day):
    """Convert the class grid to a flat dataframe for display."""
    rows = []
    for cls, grid in class_grid.items():
        for day in days_list:
            for p in range(1, periods_per_day + 1):
                val = grid[day][p]
                if val is not None:
                    subject, teacher = val
                    rows.append({
                        'Class': cls,
                        'Day': day,
                        'Period': p,
                        'Subject': subject,
                        'Teacher': teacher
                    })
    return pd.DataFrame(rows)


# ============================================================
# 📁 FILE HANDLING
# ============================================================
uploaded_file = st.file_uploader("Upload Master Timetable (Excel/CSV)", type=["xlsx", "csv"])

log_file = "Substitution_Log.csv"
if not os.path.exists(log_file):
    pd.DataFrame(columns=['Date', 'Day', 'Period', 'Absent_Teacher', 'Substitute']).to_csv(log_file, index=False)

if uploaded_file:
    if uploaded_file.name.endswith('.csv'):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)
        
    df['Class'] = df['Class'].astype(str)
    
    if 'Role' not in df.columns:
        df['Role'] = 'Regular'
        
    all_teachers = set(df['Teacher'].dropna().unique())
    history_df = pd.read_csv(log_file)

    # --- APP NAVIGATION (5 Tabs now) ---
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "🗂️ Master Editor", "📘 Class View", "🧑‍🏫 Teacher View", 
        "🧠 Smart Substitution", "🔄 Timetable Generator"
    ])

    # TAB 1: MASTER EDITOR
    with tab1:
        st.info("Edit cells directly. Any new vocational subjects added here will automatically update the whole app!")
        edited_df = st.data_editor(df, num_rows="dynamic", use_container_width=True, height=400)
        
        col_d1, col_d2 = st.columns(2)
        with col_d1:
            st.download_button(
                "💾 Download Master Timetable (CSV)",
                data=edited_df.to_csv(index=False).encode('utf-8'),
                file_name="VPS_Master_Timetable.csv",
                mime="text/csv"
            )
        with col_d2:
            st.markdown(generate_pdf(edited_df, "VPS Master Timetable"), unsafe_allow_html=True)

    # TAB 2: CLASS VIEW
    with tab2:
        col1, col2 = st.columns(2)
        with col1:
            sel_class = st.selectbox("Select Class", sorted(edited_df['Class'].unique()))
        with col2:
            sections = sorted(edited_df[edited_df['Class'] == sel_class]['Section'].unique())
            sel_section = st.selectbox("Select Section", sections)
            
        class_df = edited_df[(edited_df['Class'] == sel_class) & (edited_df['Section'] == sel_section)].sort_values('Period')
        st.dataframe(class_df, use_container_width=True, hide_index=True)
        st.markdown(generate_pdf(class_df, f"Class_{sel_class}_{sel_section}_Timetable"), unsafe_allow_html=True)

    # TAB 3: TEACHER VIEW
    with tab3:
        sel_teacher = st.selectbox("Select Teacher", sorted(list(all_teachers)))
        teacher_df = edited_df[edited_df['Teacher'] == sel_teacher].sort_values(['Day', 'Period'])
        st.dataframe(teacher_df, use_container_width=True, hide_index=True)
        st.markdown(generate_pdf(teacher_df, f"{sel_teacher}_Schedule"), unsafe_allow_html=True)

    # TAB 4: SUBSTITUTION ENGINE
    with tab4:
        if 'assigned_subs' not in st.session_state:
            st.session_state.assigned_subs = []

        col1, col2 = st.columns([1, 2])
        
        with col1:
            absent_day = st.selectbox("Day of Absence", ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"])
            absent_teacher = st.selectbox("Select Absent Teacher", sorted(list(all_teachers)))
            todays_classes = edited_df[(edited_df['Teacher'] == absent_teacher) & (edited_df['Day'] == absent_day)]
            
        with col2:
            if todays_classes.empty:
                st.success(f"✅ {absent_teacher} has no classes scheduled on {absent_day}.")
            else:
                base_workload = edited_df[edited_df['Day'] == absent_day].groupby('Teacher')['Period'].count().to_dict()
                max_period_of_day = int(edited_df['Period'].max()) if not edited_df.empty else 9
                two_weeks_ago = str(datetime.date.today() - datetime.timedelta(days=14))
                
                for period_to_cover in sorted(todays_classes['Period'].unique()):
                    class_info = todays_classes[todays_classes['Period'] == period_to_cover].iloc[0]
                    t_class, t_sec, t_sub = class_info['Class'], class_info['Section'], class_info['Subject']
                    
                    st.markdown(f"#### 🕒 Period {period_to_cover}: Class {t_class}{t_sec} ({t_sub})")
                    
                    already_assigned = next((s['Substitute'] for s in st.session_state.assigned_subs if s['Period'] == period_to_cover), None)
                    
                    if already_assigned:
                        st.success(f"🎉 Assigned to: **{already_assigned}**")
                        if st.button(f"Confirm & Save to Log (P{period_to_cover})", key=f"save_{period_to_cover}"):
                            new_log = pd.DataFrame([{'Date': str(datetime.date.today()), 'Day': absent_day, 'Period': period_to_cover, 'Absent_Teacher': absent_teacher, 'Substitute': already_assigned}])
                            new_log.to_csv(log_file, mode='a', header=False, index=False)
                            st.success("Saved to persistent log!")
                            
                        if st.button(f"Undo (P{period_to_cover})", key=f"undo_{period_to_cover}"):
                            st.session_state.assigned_subs = [s for s in st.session_state.assigned_subs if s['Period'] != period_to_cover]
                            st.rerun()
                    else:
                        busy_teaching = set(edited_df[(edited_df['Day'] == absent_day) & (edited_df['Period'] == period_to_cover)]['Teacher'].unique())
                        busy_subbing = set([s['Substitute'] for s in st.session_state.assigned_subs if s['Period'] == period_to_cover])
                        busy_teachers = busy_teaching.union(busy_subbing)
                        
                        familiar_teachers = set(edited_df[(edited_df['Class'] == t_class) & (edited_df['Section'] == t_sec)]['Teacher'].unique())
                        
                        available_candidates = []
                        
                        for teacher in all_teachers:
                            if pd.isna(teacher) or teacher == absent_teacher or teacher in busy_teachers:
                                continue
                                
                            teacher_role = edited_df[edited_df['Teacher'] == teacher]['Role'].iloc[0]
                            if teacher_role == "Level Coordinator": continue
                            
                            t_schedule = edited_df[(edited_df['Teacher'] == teacher) & (edited_df['Day'] == absent_day)]
                            t_periods = t_schedule['Period'].tolist()
                            t_periods.extend([s['Period'] for s in st.session_state.assigned_subs if s['Substitute'] == teacher])
                            
                            effective_workload = len(t_periods)
                            if effective_workload >= 7: continue
                            
                            past_14_days = len(history_df[(history_df['Substitute'] == teacher) & (history_df['Date'] >= two_weeks_ago)])
                            if teacher_role == "Subject Coordinator" and past_14_days >= 4: continue
                            
                            visual_schedule = {}
                            for p in range(1, max_period_of_day + 1):
                                if p == period_to_cover:
                                    visual_schedule[f"P{p}"] = "🟨 Sub"
                                else:
                                    teaching_now = t_schedule[t_schedule['Period'] == p]
                                    if not teaching_now.empty:
                                        visual_schedule[f"P{p}"] = f"🟥 {teaching_now.iloc[0]['Class']}{teaching_now.iloc[0]['Section']}"
                                    else:
                                        visual_schedule[f"P{p}"] = "🟩 Free"
                            
                            available_candidates.append({
                                "Name": teacher, "Load": effective_workload, "14-Day Subs": past_14_days,
                                "Familiar": teacher in familiar_teachers, **visual_schedule
                            })
                            
                        available_candidates = sorted(available_candidates, key=lambda x: x["14-Day Subs"])
                        
                        p1 = [c for c in available_candidates if c["Familiar"] and c["Load"] <= 5]
                        p2 = [c for c in available_candidates if not c["Familiar"] and c["Load"] <= 6]
                        
                        st.markdown("**Visual Guide:** 🟩 Free | 🟥 Busy | 🟨 Proposed Sub")
                        
                        col_a, col_b = st.columns(2)
                        with col_a:
                            st.markdown("**🥇 Priority 1 (Familiar, Load ≤ 5)**")
                            if p1:
                                st.dataframe(pd.DataFrame(p1).drop(columns=['Familiar']), hide_index=True)
                                sel_p1 = st.selectbox("Assign P1", ["-- Select --"] + [c["Name"] for c in p1], key=f"p1_{period_to_cover}")
                                if sel_p1 != "-- Select --":
                                    st.session_state.assigned_subs.append({'Day': absent_day, 'Period': period_to_cover, 'Substitute': sel_p1})
                                    st.rerun()
                            else: st.write("No candidates.")
                                
                        with col_b:
                            st.markdown("**🥈 Priority 2 (Available, Load ≤ 6)**")
                            if p2:
                                st.dataframe(pd.DataFrame(p2).drop(columns=['Familiar']), hide_index=True)
                                sel_p2 = st.selectbox("Assign P2", ["-- Select --"] + [c["Name"] for c in p2], key=f"p2_{period_to_cover}")
                                if sel_p2 != "-- Select --":
                                    st.session_state.assigned_subs.append({'Day': absent_day, 'Period': period_to_cover, 'Substitute': sel_p2})
                                    st.rerun()
                            else: st.write("No candidates.")
                    st.divider()

    # ============================================================
    # TAB 5: 🔄 TIMETABLE GENERATOR
    # ============================================================
    with tab5:
        st.markdown('<div class="gen-header"><h3>🔄 Auto Timetable Generator</h3>', unsafe_allow_html=True)
        st.markdown("Enter your classes, subjects, and teachers below. The system will generate a **clash-free timetable** automatically.</div>", unsafe_allow_html=True)
        
        # Initialise session state for generator data
        if 'gen_classes' not in st.session_state:
            st.session_state.gen_classes = []
        if 'gen_teachers' not in st.session_state:
            st.session_state.gen_teachers = []
        
        col_gen1, col_gen2 = st.columns([1, 1])
        
        with col_gen1:
            st.markdown("### 📚 Classes & Subjects")
            
            # Input for number of classes
            num_classes = st.number_input("Number of Classes", min_value=1, max_value=20, value=3, key="num_classes")
            
            # Ensure session state list matches
            while len(st.session_state.gen_classes) < num_classes:
                st.session_state.gen_classes.append({"name": "", "subjects": {}})
            while len(st.session_state.gen_classes) > num_classes:
                st.session_state.gen_classes.pop()
            
            for i in range(num_classes):
                with st.expander(f"**Class {i+1}**", expanded=(i==0)):
                    cls_name = st.text_input(f"Class Name", key=f"cls_name_{i}", placeholder="e.g., 6A")
                    st.session_state.gen_classes[i]["name"] = cls_name
                    
                    # Subjects for this class
                    st.markdown("**Subjects (Subject: Periods per week)**")
                    subj_input = st.text_area(
                        f"Subjects for {cls_name or f'Class {i+1}'}",
                        key=f"cls_subj_{i}",
                        placeholder="Maths:5, English:4, Science:3, Hindi:3, SST:3, Computer:2, PE:2, Art:1",
                        height=100
                    )
                    
                    # Parse subjects
                    subjects_dict = {}
                    if subj_input:
                        for item in subj_input.split(","):
                            item = item.strip()
                            if ":" in item:
                                parts = item.split(":")
                                try:
                                    subj_name = parts[0].strip()
                                    subj_count = int(parts[1].strip())
                                    if subj_name and subj_count > 0:
                                        subjects_dict[subj_name] = subj_count
                                except:
                                    pass
                    st.session_state.gen_classes[i]["subjects"] = subjects_dict
                    
                    # Show summary
                    if subjects_dict:
                        total = sum(subjects_dict.values())
                        st.caption(f"Total periods: {total}")
        
        with col_gen2:
            st.markdown("### 👨‍🏫 Teachers")
            
            num_teachers = st.number_input("Number of Teachers", min_value=1, max_value=50, value=5, key="num_teachers")
            
            while len(st.session_state.gen_teachers) < num_teachers:
                st.session_state.gen_teachers.append({"name": "", "subjects": []})
            while len(st.session_state.gen_teachers) > num_teachers:
                st.session_state.gen_teachers.pop()
            
            for i in range(num_teachers):
                with st.expander(f"**Teacher {i+1}**", expanded=(i==0)):
                    t_name = st.text_input(f"Teacher Name", key=f"t_name_{i}", placeholder="e.g., Mr. Sharma")
                    st.session_state.gen_teachers[i]["name"] = t_name
                    
                    t_subj = st.text_input(
                        f"Subjects taught by {t_name or 'Teacher'}",
                        key=f"t_subj_{i}",
                        placeholder="Maths, Science, Computer"
                    )
                    subjects_list = [s.strip() for s in t_subj.split(",") if s.strip()]
                    st.session_state.gen_teachers[i]["subjects"] = subjects_list
        
        # --- Settings ---
        st.markdown("---")
        col_s1, col_s2, col_s3 = st.columns(3)
        with col_s1:
            days_input = st.multiselect(
                "Days of Week",
                ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
                default=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
                key="gen_days"
            )
        with col_s2:
            periods_per_day = st.number_input("Periods per Day", min_value=4, max_value=12, value=8, key="gen_periods")
        with col_s3:
            st.markdown("<br>", unsafe_allow_html=True)
            generate_btn = st.button("🚀 Generate Timetable", use_container_width=True, type="primary")
        
        # --- Generate ---
        if generate_btn:
            # Validate inputs
            classes_data = {}
            for cls in st.session_state.gen_classes:
                if cls["name"] and cls["subjects"]:
                    classes_data[cls["name"]] = cls["subjects"]
            
            teachers_data = {}
            for t in st.session_state.gen_teachers:
                if t["name"] and t["subjects"]:
                    teachers_data[t["name"]] = t["subjects"]
            
            if not classes_data:
                st.error("❌ Please enter at least one class with subjects.")
            elif not teachers_data:
                st.error("❌ Please enter at least one teacher with subjects.")
            elif not days_input:
                st.error("❌ Please select at least one day.")
            else:
                with st.spinner("🔄 Generating timetable... This may take a moment."):
                    try:
                        class_grid, teacher_grid = generate_timetable(
                            classes_data, teachers_data, days_input, periods_per_day
                        )
                        
                        # Convert to dataframe
                        gen_df = grid_to_dataframe(class_grid, days_input, periods_per_day)
                        
                        st.success(f"✅ Timetable generated successfully! {len(gen_df)} periods scheduled.")
                        
                        # Store in session state for display
                        st.session_state.gen_result_df = gen_df
                        st.session_state.gen_class_grid = class_grid
                        st.session_state.gen_days = days_input
                        st.session_state.gen_periods = periods_per_day
                        st.session_state.gen_classes_data = classes_data
                        
                    except Exception as e:
                        st.error(f"❌ Error generating timetable: {str(e)}")
        
        # --- Display Results ---
        if 'gen_result_df' in st.session_state and st.session_state.gen_result_df is not None:
            st.markdown("---")
            st.markdown("### 📊 Generated Timetable")
            
            gen_df = st.session_state.gen_result_df
            class_grid = st.session_state.gen_class_grid
            days_list = st.session_state.gen_days
            periods = st.session_state.gen_periods
            classes_data = st.session_state.gen_classes_data
            
            # View by Class
            view_option = st.radio("View by:", ["Class", "Teacher"], horizontal=True)
            
            if view_option == "Class":
                view_class = st.selectbox("Select Class", sorted(gen_df['Class'].unique()), key="gen_view_class")
                
                # Display as a grid (Days × Periods)
                cls_data = class_grid[view_class]
                
                # Build a matrix display
                grid_display = []
                for p in range(1, periods + 1):
                    row = {"Period": p}
                    for day in days_list:
                        val = cls_data[day][p]
                        if val is not None:
                            row[day] = f"{val[0]} ({val[1]})"
                        else:
                            row[day] = "—"
                    grid_display.append(row)
                
                grid_df = pd.DataFrame(grid_display)
                st.dataframe(grid_df.set_index("Period"), use_container_width=True)
                
                # Download for this class
                class_only_df = gen_df[gen_df['Class'] == view_class].sort_values(['Day', 'Period'])
                st.markdown(generate_pdf(class_only_df, f"{view_class}_Generated_Timetable"), unsafe_allow_html=True)
                
            else:  # Teacher view
                all_gen_teachers = sorted(gen_df['Teacher'].unique())
                view_teacher = st.selectbox("Select Teacher", all_gen_teachers, key="gen_view_teacher")
                
                teacher_only_df = gen_df[gen_df['Teacher'] == view_teacher].sort_values(['Day', 'Period'])
                st.dataframe(teacher_only_df, use_container_width=True, hide_index=True)
                st.markdown(generate_pdf(teacher_only_df, f"{view_teacher}_Generated_Schedule"), unsafe_allow_html=True)
            
            # --- Export Full Timetable ---
            st.markdown("---")
            st.markdown("### 💾 Export Generated Timetable")
            
            col_exp1, col_exp2 = st.columns(2)
            with col_exp1:
                csv_data = gen_df.to_csv(index=False).encode('utf-8')
                st.download_button(
                    "📥 Download as CSV",
                    data=csv_data,
                    file_name="Generated_Timetable.csv",
                    mime="text/csv",
                    use_container_width=True
                )
            with col_exp2:
                st.markdown(generate_pdf(gen_df, "Complete_Generated_Timetable"), unsafe_allow_html=True)
            
            # --- Option to use this timetable in the app ---
            st.markdown("---")
            st.markdown("### 📋 Use This Timetable in the App")
            st.info("💡 You can download the CSV above and upload it in the **Master Editor** tab to use it with the Substitution Manager.")
            
            # Quick preview of what was generated
            with st.expander("📊 Summary: Periods per Class"):
                summary = gen_df.groupby('Class').size().reset_index(name='Total Periods')
                st.dataframe(summary, hide_index=True, use_container_width=True)
            
            with st.expander("👨‍🏫 Summary: Workload per Teacher"):
                workload = gen_df.groupby('Teacher').size().reset_index(name='Total Periods').sort_values('Total Periods', ascending=False)
                st.dataframe(workload, hide_index=True, use_container_width=True)

else:
    st.info("👆 Please upload your Master Timetable to begin.")
